import Head from "next/head";
import Container from "../components/uiComponents/Container";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Chota Ninja</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ninja.ico" />
      </Head>

      {/* Homepage Hero Section  */}
      <Container>
        <div className="md:flex justify-between place-items-center">
          <content className="space-y-6">
            <h2 className=" font-Ribeye text-6xl">
              <span className="text-blue-600">Simple-Ize</span> Your <br />{" "}
              advanced link.
            </h2>
            <p className="text-gray-500 max-w-lg">
              Share your content to audience and maximize potential of your
              social bio link in just one click.
            </p>
          </content>
          <Image
            className=" absolute"
            src="/Images/homepage.svg"
            alt="homepage"
            width="550"
            height="450"
          />
        </div>
      </Container>

      {/* Create Anonymous Link  */}
      <div className="mt-6">
        <hr />
        <Container>
          <div className="flex gap-6 py-6">
            <input
              placeholder="Shorten your link"
              className="px-3 py-3 outline-none border border-gray-200 rounded-lg w-full text-gray-600"
            />
            <button className="bg-blue-600 px-10 py-3 rounded-lg text-white cursor-pointer hover:bg-blue-500 focus:ring focus:ring-blue-300 transform duration-300">
              Shorten
            </button>
          </div>
        </Container>
        <hr />
      </div>
    </div>
  );
}
